/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinformationclient;

import java.awt.*;
import javax.swing.*;

import com.sun.swing.internal.plaf.basic.resources.basic_it;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import musicinformationclient.socket.WebView;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Administrator
 */
public class AlbumSingsPanel extends javax.swing.JPanel {

private SongsPanelinAlbum.SendLink sendLink;
    /**
     * Creates new form AlbumSingsPanel
     */
    public AlbumSingsPanel() {
        initComponents();
    }
    public AlbumSingsPanel(String name, String info)  {

        System.out.println("đi tới chỗ này 4" + info);
        System.out.println("đi tới chỗ này 4" + name);

        initComponents();
        loadThongTinCaSi(name, info);
        
    }
    public AlbumSingsPanel(JSONArray array,String ok,SongsPanelinAlbum.SendLink sendLink)  {
        this.sendLink=sendLink;
        initComponents();
        loadSongs(array,ok);
    }
    public AlbumSingsPanel(JSONArray array,int ok,SongsPanelinAlbum.SendLink sendLink)  {
        this.sendLink=sendLink;
        initComponents();
        loadMvs(array,ok);
    }
    public AlbumSingsPanel(String tenAlbum ,JSONArray array , String add,SongsPanelinAlbum.SendLink sendLink) {
        this.sendLink=sendLink;
        System.out.println("đi tới chỗ này 6");
        initComponents();
        add6Album(tenAlbum,array,add);
    }
    public AlbumSingsPanel(JSONObject obj) {

        System.out.println("đi tới chỗ này 8");
        initComponents();
        loadThongtinbaihat(obj);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenAlbum = new javax.swing.JLabel();
        jPanelDanhSachAlBum = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelTenAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTenAlbum.setText("jLabel1");

        jPanelDanhSachAlBum.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDanhSachAlBumLayout = new javax.swing.GroupLayout(jPanelDanhSachAlBum);
        jPanelDanhSachAlBum.setLayout(jPanelDanhSachAlBumLayout);
        jPanelDanhSachAlBumLayout.setHorizontalGroup(
            jPanelDanhSachAlBumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDanhSachAlBumLayout.setVerticalGroup(
            jPanelDanhSachAlBumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDanhSachAlBum, javax.swing.GroupLayout.PREFERRED_SIZE,1200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTenAlbum)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTenAlbum)
                .addGap(5, 5, 5)
                .addComponent(jPanelDanhSachAlBum,  javax.swing.GroupLayout.PREFERRED_SIZE,800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTenAlbum;
    private javax.swing.JPanel jPanelDanhSachAlBum;
    // End of variables declaration//GEN-END:variables
private void loadThongTinCaSi(String name, String info) {
        //jPanelDanhSachAlBum.removeAll();
        String [] tmp = info.split(",");
        JPanel jPanel_tmp_thongtin = new JPanel();
        //jPanel_tmp_thongtin.setSize(200,100);
        //jPanel_tmp_thongtin.setLayout(new GridLayout(tmp.length+2, 1));

        JLabel  jlabname = new JLabel("Tên ca sĩ:"+name);
        jlabname.setFont(new java.awt.Font("Tahoma", 0, 14));
        jPanel_tmp_thongtin.add(jlabname);
        JLabel [] jlabtt = new JLabel[tmp.length+2];
        System.out.println("legth"+tmp.length);
        for (int i = 0; i < tmp.length; i++) {
            System.out.println("xuat ra "+i+"||"+tmp[i]);
            jlabtt[i]=new JLabel(tmp[i]);
            jlabtt[i].setFont(new java.awt.Font("Tahoma", 0, 14));
            jPanel_tmp_thongtin.add(jlabtt[i]);
            jPanel_tmp_thongtin.add(new JLabel("<html> <br></html>"));
        }
        JTextArea jTextAreaTT= new JTextArea();
        jTextAreaTT.setText(info);
        jTextAreaTT.setLineWrap(true);
        jTextAreaTT.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabelTenAlbum.setText("Thông tin ca sĩ:");
    JScrollPane jScrollPane=new JScrollPane(jTextAreaTT);
    jScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    jPanelDanhSachAlBum.removeAll();
    jPanelDanhSachAlBum.setLayout(new GridLayout(1,1));
    jPanelDanhSachAlBum.add(jScrollPane);

    jPanelDanhSachAlBum.validate();
    jPanelDanhSachAlBum.repaint();
    }
    public void loadThongtinbaihat(JSONObject obj)
    {
        String name=obj.getJSONObject("data").getString("name");
        String loibaihat=obj.getJSONObject("data").getString("lyrics");
        String tennhacsi=obj.getJSONObject("data").getString("composerName");
        String tencasi=obj.getJSONObject("data").getString("singerName");
        String audio=obj.getJSONObject("data").getString("audio");
        jLabelTenAlbum.setText("Tên bài hát :" + name+"    "+"Tên nhạc sĩ:"+tencasi+"    "+"Tên nhạc sĩ:"+tennhacsi);
        JPanel jPanel_tmp= new JPanel();
        jPanel_tmp.setLayout(new GridLayout(2,1));
        String[] tmp=loibaihat.split("\\n<br>");
        JPanel jPanel = new JPanel();
        jPanel.setLayout(new GridLayout(tmp.length+1,1));
        jPanel.add(new JLabel("Lời bài hát"));
        for (int i=0;i<tmp.length;i++)
        {
            jPanel.add(new Label(tmp[i]));
        }
        jPanel.setBackground(Color.white);
        //JScrollPane jScrollPane1= new JScrollPane(jPanel);
        jPanel_tmp.add(jPanel);
        JFXPanel jfxPanel1=new JFXPanel();
        JFXPanel jfxPanel = new WebView(audio);

        Platform.runLater( new Runnable ()  {
            @Override
            public void run()
            {
                javafx.scene.web.WebView webView = new javafx.scene.web.WebView();
                jfxPanel1.setScene(new Scene(webView));
                webView.getEngine().load(audio);
                System.out.println("webview");
            }

        });
        jPanel_tmp.add(jfxPanel);
        JScrollPane jScrollPane = new JScrollPane(jPanel_tmp);
        jScrollPane.getVerticalScrollBar().setUnitIncrement(16);
                jPanelDanhSachAlBum.removeAll();
                jPanelDanhSachAlBum.setLayout(new GridLayout(1,1));
                jPanelDanhSachAlBum.add(jScrollPane);
                jPanelDanhSachAlBum.validate();
                jPanelDanhSachAlBum.repaint();
    }
    private  void add6Album(String tenAlbum,JSONArray arr, String add)
    {

        int length=arr.length();
        /*if(arr.length()<6)
        {
            length=arr.length();
        }*/
        JPanel jPanel_tmp_add_Al=new JPanel();
        jPanel_tmp_add_Al.setSize(400,600);
        //jPanel_tmp_add_Al.setLayout(new GridLayout(length,1));
        jPanel_tmp_add_Al.setLayout(new GridLayout(length*2,1));
        JPanel jPanel = new JPanel();
        //jPanel.setLayout(new GridLayout(length,1));
        jPanel.setLayout(new BoxLayout(jPanel, BoxLayout.Y_AXIS));
        for(int i=0;i<length;i++)
        {


            /*jPanel_tmp_add_Al.add(new JLabel(arr.getJSONObject(i).getString("name")));

            jPanel_tmp_add_Al.add(new JLabel(arr.getJSONObject(i).getString("audio")));*/
            String tenbaihat = arr.getJSONObject(i).getString("name");

            //String tencasi = arr.getJSONObject(i).getString("artists_names");
            String anhcasi = arr.getJSONObject(i).getString("thumbnail");
            String infocasi = arr.getJSONObject(i).getString("audio");;
            JPanel tmp=new SongsPanelinAlbum(tenbaihat,anhcasi,infocasi,"",sendLink );
            tmp.setBackground(Color.white);
            jPanel.add(tmp);
            jPanel.setBackground(Color.white);
            ///jPanel.add(new JLabel("<html><br></html>"));

        }
        JScrollPane jScrollPane = new JScrollPane(jPanel);
        jScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        jLabelTenAlbum.setText(tenAlbum);
        jPanelDanhSachAlBum.removeAll();
        jPanelDanhSachAlBum.setLayout(new GridLayout());
        jPanelDanhSachAlBum.add(jScrollPane);

        jPanelDanhSachAlBum.validate();
        jPanelDanhSachAlBum.repaint();

    }
    private void loadSongs(JSONArray arr,String song)
    {
        JPanel jPanelSongs= new JPanel();
        jPanelSongs.setLayout(new GridLayout(arr.length(),1));
        for (int i=0;i<arr.length();i++)
        {String tenbaihat = arr.getJSONObject(i).getString("name");

            //String tencasi = arr.getJSONObject(i).getString("artists_names");
            String anhcasi = arr.getJSONObject(i).getString("thumbnail");
            String infocasi = arr.getJSONObject(i).getString("audio");;
            JPanel tmp=new SongsPanelinAlbum(tenbaihat,anhcasi,infocasi,"", sendLink);
            tmp.setBackground(Color.white);
            jPanelSongs.add(tmp);
        }
        JScrollPane jScrollPane = new JScrollPane(jPanelSongs);
        jScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        jPanelDanhSachAlBum.removeAll();
        jPanelDanhSachAlBum.setLayout(new GridLayout(1,1));
        jPanelDanhSachAlBum.add(jScrollPane);
        jLabelTenAlbum.setText("");
        jPanelDanhSachAlBum.validate();
        jPanelDanhSachAlBum.repaint();
    }
    private void loadMvs(JSONArray arr,int ok)
    {
        JPanel jPanelSongs= new JPanel();
        jPanelSongs.setLayout(new GridLayout(arr.length(),1));
        for (int i=0;i<arr.length();i++)
        {String tenbaihat = arr.getJSONObject(i).getString("name");

            //String tencasi = arr.getJSONObject(i).getString("artists_names");
            String anhcasi = arr.getJSONObject(i).getString("thumbnail");
            String infocasi = arr.getJSONObject(i).getString("video");;
            JPanel tmp=new SongsPanelinAlbum(tenbaihat,anhcasi,infocasi,"", sendLink);
            tmp.setBackground(Color.white);
            jPanelSongs.add(tmp);
        }
        JScrollPane jScrollPane = new JScrollPane(jPanelSongs);
        jScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        jPanelDanhSachAlBum.removeAll();
        jPanelDanhSachAlBum.setLayout(new GridLayout(1,1));
        jPanelDanhSachAlBum.add(jScrollPane);
        jLabelTenAlbum.setText("");
        jPanelDanhSachAlBum.validate();
        jPanelDanhSachAlBum.repaint();
    }

    private void loadData() {

    }
}
