/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinformationclient;

import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import musicinformationclient.socket.WebView;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Administrator
 */
public class Jpanel1BaiHat extends javax.swing.JPanel {
    public interface SendBack
    {
        void sendBackInfoCasi();

    }
    private SendBack sendBack;
    /**
     * Creates new form Jpanel1BaiHat
     */
    public Jpanel1BaiHat(String name,String link,SendBack sendBack) {
        this.sendBack = sendBack;
        initComponents();
        loadData(name,link);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTenBaiHat = new javax.swing.JLabel();
        jPanelBaiHat = new javax.swing.JPanel();

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelTenBaiHat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTenBaiHat.setText("Ten bai hat");

        javax.swing.GroupLayout jPanelBaiHatLayout = new javax.swing.GroupLayout(jPanelBaiHat);
        jPanelBaiHat.setLayout(jPanelBaiHatLayout);
        jPanelBaiHatLayout.setHorizontalGroup(
            jPanelBaiHatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelBaiHatLayout.setVerticalGroup(
            jPanelBaiHatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelTenBaiHat)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelBaiHat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelTenBaiHat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBaiHat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonBack)
                .addContainerGap(646, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
sendBack.sendBackInfoCasi();
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabelTenBaiHat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBaiHat;
    // End of variables declaration//GEN-END:variables
private void loadData(String name,String link)
{System.out.println(link);

    JFXPanel jfxPanel = new JFXPanel();
    JFXPanel jfxPanel1 = new WebView(link);
    jPanel1.removeAll();
    jPanelBaiHat.removeAll();
    Platform.runLater( new Runnable ()  {
        @Override
                public void run()
        {
            javafx.scene.web.WebView webView = new javafx.scene.web.WebView();
            jfxPanel.setScene(new Scene(webView));
            webView.getEngine().load(link);
            System.out.println("webview");
        }

    });
//    JPanel tmp = new JPanel();
//    tmp.setBackground(Color.red);
//    tmp.add(new JLabel("ok"));
    jLabelTenBaiHat.setText(name);
    jPanel1.removeAll();
    jPanelBaiHat.removeAll();
    jPanelBaiHat.setLayout(new GridLayout());
    jPanelBaiHat.add(jfxPanel1);
    //jPanelBaiHat.setBackground(Color.red);
    jPanelBaiHat.validate();
    jPanelBaiHat.repaint();
    jPanel1.validate();
    jPanel1.repaint();

}
}
