/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinformationclient;

import org.json.JSONArray;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Administrator
 */
public class KhungChuaAlbum extends javax.swing.JPanel {
private SongsPanelinAlbum.SendLink sendLink;
    /**
     * Creates new form KhungChuaAlbum
     */
    public KhungChuaAlbum(JSONArray array,SongsPanelinAlbum.SendLink sendLink) {
        this.sendLink=sendLink;
        initComponents();
        loadAlbum(array);
    }
    public KhungChuaAlbum(JSONArray array,String song,SongsPanelinAlbum.SendLink sendLink) {
        this.sendLink=sendLink;
        initComponents();
        loadSongs(array,song);
    }
    public KhungChuaAlbum(JSONArray array,int ok,SongsPanelinAlbum.SendLink sendLink) {
        this.sendLink=sendLink;
        initComponents();
        loadMvs(array,ok);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListAlbum = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelListAlbum.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelListAlbumLayout = new javax.swing.GroupLayout(jPanelListAlbum);
        jPanelListAlbum.setLayout(jPanelListAlbumLayout);
        jPanelListAlbumLayout.setHorizontalGroup(
            jPanelListAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelListAlbumLayout.setVerticalGroup(
            jPanelListAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Album:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 586, Short.MAX_VALUE))
            .addComponent(jPanelListAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListAlbum, javax.swing.GroupLayout.PREFERRED_SIZE,850, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadAlbum (JSONArray arr)
    {
        JPanel jPanel_tmp_loadALbum =new JPanel();

        int length=arr.length();
        /*if(arr.length()<6)
        {
            length=arr.length();
        }*/
        jPanel_tmp_loadALbum.setLayout(new GridLayout(length,1));
        for(int i=0;i<length;i++)
        {

            JPanel jPanel=new AlbumSingsPanel(arr.getJSONObject(i).getString("name"),arr.getJSONObject(i).getJSONArray("songs"),"ok",sendLink);
            jPanel_tmp_loadALbum.add(jPanel);
        }
        JScrollPane jScrollPane = new JScrollPane(jPanel_tmp_loadALbum);
        jScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        jPanelListAlbum.removeAll();
        jPanelListAlbum.setLayout(new GridLayout(1,1));
        jPanelListAlbum.add(jScrollPane);

        jPanelListAlbum.validate();
        jPanelListAlbum.repaint();


    }
    private void loadSongs(JSONArray arr,String song)
    {

        jPanelListAlbum.removeAll();
        jPanelListAlbum.setLayout(new GridLayout(1,1));
        jPanelListAlbum.add(new AlbumSingsPanel(arr,song,sendLink));
        jLabel1.setText("Danh sách bài hát:");
        jPanelListAlbum.validate();
        jPanelListAlbum.repaint();
    }
    private void loadMvs(JSONArray arr,int ok)
    {

        jPanelListAlbum.removeAll();
        jPanelListAlbum.setLayout(new GridLayout(1,1));
        jPanelListAlbum.add(new AlbumSingsPanel(arr,ok,sendLink));
        jLabel1.setText("Danh sách MV:");
        jPanelListAlbum.validate();
        jPanelListAlbum.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelListAlbum;
    // End of variables declaration//GEN-END:variables
}
