/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinformationclient;

import java.awt.*;
import javax.swing.*;
import musicinformationclient.socket.SocketClient;
import org.json.JSONArray;
import org.json.JSONObject;
/**
 *
 * @author Administrator
 */
public class listResultPanel extends javax.swing.JPanel implements SongsPanelinAlbum.SendLink {
        JLabel loading;
        private eventClick eClick;

    @Override
    public void send(String name, String link) {
        load1BaiHat(name,link);
    }

    public interface eventClick
        {
            void sendClick();
        }
    /**
     * Creates new form listResultPanel
     */
        private singerPanel.Event event;
    public listResultPanel(singerPanel.Event event,eventClick e) {
        this.event = event;
        this.eClick=e;
        initComponents();
        initUI();
    }
    
    public void initSinger(String inputString) {
        initdata(inputString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listresultPanel = new javax.swing.JPanel();
        jPanelTenDanhSach = new javax.swing.JPanel();
        jPanelListCaSi = new javax.swing.JPanel();
        jlabTenDanhSach = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        listresultPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTenDanhSach.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTenDanhSachLayout = new javax.swing.GroupLayout(jPanelTenDanhSach);
        jPanelTenDanhSach.setLayout(jPanelTenDanhSachLayout);
        jPanelTenDanhSachLayout.setHorizontalGroup(
            jPanelTenDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanelTenDanhSachLayout.setVerticalGroup(
            jPanelTenDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanelListCaSi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelListCaSiLayout = new javax.swing.GroupLayout(jPanelListCaSi);
        jPanelListCaSi.setLayout(jPanelListCaSiLayout);
        jPanelListCaSiLayout.setHorizontalGroup(
            jPanelListCaSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelListCaSiLayout.setVerticalGroup(
            jPanelListCaSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        jlabTenDanhSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listresultPanelLayout = new javax.swing.GroupLayout(listresultPanel);
        listresultPanel.setLayout(listresultPanelLayout);
        listresultPanelLayout.setHorizontalGroup(
            listresultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listresultPanelLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTenDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelListCaSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(listresultPanelLayout.createSequentialGroup()
                .addComponent(jlabTenDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        listresultPanelLayout.setVerticalGroup(
            listresultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listresultPanelLayout.createSequentialGroup()
                .addGroup(listresultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTenDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(4, 4, 4)
                .addComponent(jlabTenDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listresultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listresultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        eClick.sendClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelListCaSi;
    private javax.swing.JPanel jPanelTenDanhSach;
    private javax.swing.JLabel jlabTenDanhSach;
    private javax.swing.JPanel listresultPanel;
    // End of variables declaration//GEN-END:variables

    private void initdata(String input)
    {String [] tmp = input.split("###");
     if(tmp[0].contains("RESULTSEARCHCASI"))
     {
         loadData(input);
     }
     if(tmp[0].contains("RESULTSEARCHBAIHAT"))
     {
         loadBaiHatData(input);
     }
     if(tmp[0].contains("RESULTINFOCASI"))
     {
         System.out.println("đi tới chỗ này 1");
     loadThongTinCaSi(input);
     }
        
    }
    private void load1BaiHat(String name,String link)
    {
        JPanel jPanel=new Jpanel1BaiHat(name,link);
        jlabTenDanhSach.setVisible(false);
        jButton1.setVisible(false);
        jPanelListCaSi.removeAll();
        jPanelListCaSi.setLayout(new GridLayout());
        jPanelListCaSi.add(jPanel);
        jPanelListCaSi.validate();
        jPanelListCaSi.repaint();
    }
    private void loadData( String inputString) {
        
        jPanelListCaSi.removeAll();
        jPanelListCaSi.setLayout(new GridLayout(1,1));
        loading = new JLabel("oke");
        jPanelListCaSi.add(loading);
        jPanelListCaSi.validate();
        System.err.println("toi day roi");
        JPanel jpanel = new JPanel();
        jlabTenDanhSach.setText("Danh sách ca sĩ:");
        String[] tmp = inputString.split("###");
        JSONArray arr = new JSONArray(tmp[1]);
            jpanel.setLayout(new GridLayout(arr.length(),1));
        for(int i =0; i<arr.length(); i++) {
            String name = arr.getJSONObject(i).getString("name");
            String image =arr.getJSONObject(i).getString("thumbnail");
            String info =arr.getJSONObject(i).getString("info");
            jpanel.add(new singerPanel(name,image,info, event));
        }
        jButton1.setVisible(false);
        jPanelListCaSi.removeAll();
        jPanelListCaSi.setLayout(new GridLayout());
        jPanelListCaSi.add(jpanel);
        jPanelListCaSi.validate();
        jPanelListCaSi.repaint();
        
    }
    private void loadBaiHatData( String inputString) {
        
        jPanelListCaSi.removeAll();
        jPanelListCaSi.setLayout(new GridLayout(1,1));
        loading = new JLabel("oke");
        jPanelListCaSi.add(loading);
        jPanelListCaSi.validate();
        System.err.println("toi day roi");
        JPanel jpanel = new JPanel();
        jlabTenDanhSach.setText("Danh sách bài hát:");
        String[] tmp = inputString.split("###");
        JSONArray arr = new JSONArray(tmp[1]);
            jpanel.setLayout(new GridLayout(arr.length(),1));
        for(int i =0; i<arr.length(); i++) {
            String tenbaihat = arr.getJSONObject(i).getString("name");

            String tencasi = arr.getJSONObject(i).getString("artists_names");
            String anhcasi = arr.getJSONObject(i).getString("thumbnail");
            String infocasi = arr.getJSONObject(i).getString("info");;
            jpanel.add(new SongsPanel(tenbaihat,anhcasi,infocasi,tencasi));
        }
        jButton1.setVisible(false);
        jPanelListCaSi.removeAll();
        jPanelListCaSi.setLayout(new GridLayout());
        jPanelListCaSi.add(jpanel);
        jPanelListCaSi.validate();
        jPanelListCaSi.repaint();
        
    }
    private void loadThongTinCaSi(String inputData)
    {   jPanelListCaSi.removeAll();
        String[] tmp = inputData.split("###");
        JSONObject obj = new JSONObject(tmp[1]);
        String name= obj.getJSONObject("data").getString("name");
        String info= obj.getJSONObject("data").getString("info");
        JSONArray album =obj.getJSONObject("data").getJSONArray("album");
        JSONArray songs=obj.getJSONObject("data").getJSONArray("song");
        JSONArray mvs=obj.getJSONObject("data").getJSONArray("mv");
        System.out.println("đi tới chỗ này 2");

//        JPanel jPanel = new ListInfoSingPanel(inputData);
        jPanelListCaSi.setLayout(new GridLayout(4,1));
         JPanel jPanel = new AlbumSingsPanel(name,info);
        jPanelListCaSi.add(jPanel);
        JPanel jPanelAlbum = new KhungChuaAlbum(album,this);
        JPanel jPanelSongs= new KhungChuaAlbum(songs,"ok",this);
        JPanel jPanelMvs= new KhungChuaAlbum(mvs,1,this);
        jPanelListCaSi.add(jPanelAlbum);
        jPanelListCaSi.add(jPanelSongs);
       jPanelListCaSi.add(jPanelMvs);
        jlabTenDanhSach.setText("Thông tin Ca sĩ:");
        //jPanelListCaSi.setLayout(new GridLayout());

        jPanelListCaSi.validate();
        jPanelListCaSi.repaint();
    }
    private void loadThongTinBaiHat(String inputData)
    {
        jPanelListCaSi.removeAll();
        
    }
     private void showLoading() {
        
         jPanelListCaSi.setVisible(false);
         loading.setVisible(true);
         invalidate();
    }
     
    private void dismisLoading(){
         jPanelListCaSi.setVisible(true);
         loading.setVisible(false);
         invalidate();
    
    }
    private void initUI() {
        //Icon loadingImage = new ImageIcon(this.getClass().getResource("./img/200.gif"));
//        loading = new JLabel(loadingImage);
        loading = new JLabel("oke");
        loading.setVisible(false);
        loading.setSize(200, 200);
        loading.setLocation(600, 150);
        jPanelListCaSi.add(loading,BorderLayout.CENTER);
    }

    
}
