/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinformationclient;

import java.awt.Image;
import javax.swing.JPanel;
import musicinformationclient.socket.Images;

/**
 *
 * @author Administrator
 */
public class singerPanel extends javax.swing.JPanel {

    /**
     * Creates new form singerPanel
     */
    private Event event;
    
    public singerPanel(String name, String image,String info, Event event) {
        this.event = event;
        initComponents();
        Images img = new Images();
        JPanel jPanel_tmp=img.show_image(image,100,100);
        jPanelAnh.add(jPanel_tmp);
        nameLabel.setText("Tên ca sĩ: "+name);
        jLabelInfo.setText(info);
        jLabelInfo.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelAnh = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jButtonXemThongTin = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAnh.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelAnhLayout = new javax.swing.GroupLayout(jPanelAnh);
        jPanelAnh.setLayout(jPanelAnhLayout);
        jPanelAnhLayout.setHorizontalGroup(
            jPanelAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAnhLayout.setVerticalGroup(
            jPanelAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jButtonXemThongTin.setBackground(new java.awt.Color(153, 255, 255));
        jButtonXemThongTin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonXemThongTin.setForeground(new java.awt.Color(255, 51, 51));
        jButtonXemThongTin.setText("Xem Thông tin");
        jButtonXemThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXemThongTinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonXemThongTin)
                            .addComponent(jLabelInfo))
                        .addGap(0, 415, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonXemThongTin)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonXemThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemThongTinActionPerformed
        //String sendDatas = nameLabel.getText();
        //System.err.println(sendDatas);
//        MainFrame main = new MainFrame();
//        main.loadInfoSingData("oke");
        System.out.println(jLabelInfo.getText());
        // TODO add your handling code here:
        event.send(jLabelInfo.getText());
    }//GEN-LAST:event_jButtonXemThongTinActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonXemThongTin;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAnh;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    public interface Event {

        void send(String data);
    }
    
}


